name: ar_shopping_app
description: "A new Flutter project for AR shopping."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  ar_flutter_plugin: ^0.7.3
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  path_provider: ^2.0.14
  permission_handler: ^10.4.5
  vector_math: ^2.1.4
  webview_flutter: ^4.0.7

# This section forces the use of a newer permission_handler version
dependency_overrides:
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"

  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/models/bed.glb
    - assets/models/table.glb
    - assets/models/sofa.glb
    - assets/models/lamp.glb
    - assets/models/Box.glb
    - assets/models/Duck.glb

# ADDED THIS ENTIRE SECTION AT THE END FOR THE APP ICON
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
